version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install yarn 
            - run: yarn install
            - run: lerna bootstrap
            - run: cd packages/service 
            - run: yarn 
            - run: yarn test  
workflows:
    build-and-test:
      jobs:
        - build-and-test